#---------uv------------------
FROM --platform=$BUILDPLATFORM ghcr.io/astral-sh/uv:latest AS uv_host 

#---------builder------------
FROM --platform=$BUILDPLATFORM python:3.13-slim AS builder
WORKDIR /project
ARG TARGETOS
ARG TARGETARCH
RUN echo "Building for $TARGETOS/$TARGETARCH"

# install uv
COPY --from=uv_host /uv /usr/bin/uv

# build package
WORKDIR /project
COPY pyproject.toml uv.lock build.sh /project/
COPY src /project/src

RUN bash build.sh

#---------runner------------
FROM public.ecr.aws/lambda/python:3.13


COPY --from=builder /project/package /project
ENV PYTHONPATH=/project

CMD ["app.awslambda.handler"]
